// The Gen 4 dex modules are generated by the same scripts as Gen 7's with
// the generation as an argument; these pin the generation-specific facts the
// engine will rely on for a Gen 4 game.
import test from 'node:test';
import assert from 'node:assert/strict';

const { GEN4_TYPES, GEN4_TYPE_DAMAGE_TAKEN } = await import(
  '../src/generated/gen4TypeChart.generated.js',
);
const { GEN4_PROGRESSION_SPECIES } = await import(
  '../src/generated/gen4ProgressionSpecies.generated.js',
);
const { LINE_REPRESENTATIVE_CANDIDATES } = await import(
  '../src/generated/gen4LineRepresentativeCandidates.generated.js',
);
const { MOVE_META } = await import('../src/generated/gen4MoveMeta.generated.js');
const { GEN4_BASE_STATS } = await import(
  '../src/generated/gen4BaseStats.generated.js',
);

test('Gen 4 has 17 types, no Fairy, and Steel still resists Ghost and Dark', () => {
  assert.equal(GEN4_TYPES.length, 17);
  assert.ok(!GEN4_TYPES.includes('Fairy'));
  assert.equal(GEN4_TYPE_DAMAGE_TAKEN.Steel.Ghost, 2);
  assert.equal(GEN4_TYPE_DAMAGE_TAKEN.Steel.Dark, 2);
});

test('Gen 4 species are the standard dex through Sinnoh, with closed evolution links', () => {
  const ids = new Set(Object.keys(GEN4_PROGRESSION_SPECIES));
  assert.ok(ids.has('garchomp') && ids.has('rotomwash'));
  assert.ok(!ids.has('sylveon') && !ids.has('snivy'));
  for (const species of Object.values(GEN4_PROGRESSION_SPECIES)) {
    assert.equal(species.isMega, false, species.id);
    for (const evo of species.evos) assert.ok(ids.has(evo), `${species.id} -> ${evo}`);
    if (species.prevoId) assert.ok(ids.has(species.prevoId), species.id);
  }
  // Move-based evolutions read the pre-evolution's Gen 4 learnset.
  assert.equal(GEN4_PROGRESSION_SPECIES.tangrowth.evoMoveLevel, 33);
});

test('Gen 4 lines stop at Gen 4 forms and carry no megas', () => {
  const eevee = LINE_REPRESENTATIVE_CANDIDATES.eevee.map((form) => form.id);
  assert.deepEqual(eevee, [
    'eevee', 'vaporeon', 'jolteon', 'flareon', 'espeon', 'umbreon', 'leafeon',
    'glaceon',
  ]);
  assert.ok(!('charizardmegax' in LINE_REPRESENTATIVE_CANDIDATES));
  for (const members of Object.values(LINE_REPRESENTATIVE_CANDIDATES)) {
    assert.ok(members.every((form) => !form.isMega));
  }
});

test('Gen 4 moves and stats exclude later generations', () => {
  assert.ok('stoneedge' in MOVE_META && !('scald' in MOVE_META));
  assert.equal(MOVE_META.hiddenpower.basePower, 70);
  assert.ok('garchomp' in GEN4_BASE_STATS && !('zoroark' in GEN4_BASE_STATS));
});
